### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by AeriaVelocity** [Aaron-Buckles/solitaire#2]
```python
Traceback (most recent call last):
  File "/home/that1m8head/Desktop/solitaire-master/game/solitaire_tests.py", line 9, in setUp
    self.deck = Deck()
  File "/home/that1m8head/Desktop/solitaire-master/game/deck.py", line 32, in __init__
    self.card_back_image = pygame.image.load(name_of_image)
FileNotFoundError: No such file or directory.
```
Seems like it can't find an image.
Full output:
```bash
<that1m8head@my-epic-arch-stick>:~ $ python '/home/that1m8head/Desktop/solitaire-master/game/solitaire_tests.py' 
pygame 2.0.1 (SDL 2.0.14, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
EEE
======================================================================
ERROR: test_deck_size (__main__.SolitaireTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/that1m8head/Desktop/solitaire-master/game/solitaire_tests.py", line 9, in setUp
    self.deck = Deck()
  File "/home/that1m8head/Desktop/solitaire-master/game/deck.py", line 32, in __init__
    self.card_back_image = pygame.image.load(name_of_image)
FileNotFoundError: No such file or directory.

======================================================================
ERROR: test_pile_selection (__main__.SolitaireTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/that1m8head/Desktop/solitaire-master/game/solitaire_tests.py", line 9, in setUp
    self.deck = Deck()
  File "/home/that1m8head/Desktop/solitaire-master/game/deck.py", line 32, in __init__
    self.card_back_image = pygame.image.load(name_of_image)
FileNotFoundError: No such file or directory.

======================================================================
ERROR: test_pile_sizes (__main__.SolitaireTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/that1m8head/Desktop/solitaire-master/game/solitaire_tests.py", line 9, in setUp
    self.deck = Deck()
  File "/home/that1m8head/Desktop/solitaire-master/game/deck.py", line 32, in __init__
    self.card_back_image = pygame.image.load(name_of_image)
FileNotFoundError: No such file or directory.

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (errors=3)
```

**Comment by csirick2020** [comment]
Could this be because you don't have the image files downloaded and/or in the right directory?
